// TODO: Replace with API call to /api/properties with filter params

import { Property, PropertyDetails } from './types'

export const mockProperties: Property[] = [
  {
    id: '1',
    slug: 'premium-2bhk-flat-tilakwadi',
    title: 'Premium 2BHK Flat in Tilakwadi',
    area: 'Tilakwadi',
    city: 'Belagavi',
    propertyType: 'APARTMENT',
    priceMin: 4500000,
    priceMax: 5500000,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 980,
    badge: 'FEATURED',
    isFeatured: true,
    coverImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    status: 'ACTIVE',
  },
  {
    id: '2',
    slug: 'spacious-3bhk-house-sadashivnagar',
    title: 'Spacious 3BHK House in Sadashivnagar',
    area: 'Sadashivnagar',
    city: 'Belagavi',
    propertyType: 'HOUSE',
    priceMin: 8500000,
    priceMax: 9500000,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1800,
    badge: 'NEW',
    isFeatured: true,
    coverImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    status: 'ACTIVE',
  },
  {
    id: '3',
    slug: 'corner-plot-hindwadi',
    title: 'Corner Plot in Hindwadi',
    area: 'Hindwadi',
    city: 'Belagavi',
    propertyType: 'PLOT',
    priceMin: 3500000,
    priceMax: 4000000,
    bedrooms: null,
    bathrooms: null,
    areaSqft: 2400,
    badge: 'HOT',
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    status: 'ACTIVE',
  },
  {
    id: '4',
    slug: 'luxury-villa-shahapur',
    title: 'Luxury Villa with Garden in Shahapur',
    area: 'Shahapur',
    city: 'Belagavi',
    propertyType: 'VILLA',
    priceMin: 15000000,
    priceMax: 18000000,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3200,
    badge: 'FEATURED',
    isFeatured: true,
    coverImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    status: 'ACTIVE',
  },
  {
    id: '5',
    slug: 'commercial-shop-camp',
    title: 'Prime Commercial Shop in Camp Area',
    area: 'Camp',
    city: 'Belagavi',
    propertyType: 'COMMERCIAL',
    priceMin: 7500000,
    priceMax: 8500000,
    bedrooms: null,
    bathrooms: 1,
    areaSqft: 650,
    badge: null,
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    status: 'ACTIVE',
  },
  {
    id: '6',
    slug: 'modern-1bhk-flat-vadgaon',
    title: 'Modern 1BHK Flat in Vadgaon',
    area: 'Vadgaon',
    city: 'Belagavi',
    propertyType: 'APARTMENT',
    priceMin: 2800000,
    priceMax: 3200000,
    bedrooms: 1,
    bathrooms: 1,
    areaSqft: 550,
    badge: 'NEW',
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    status: 'ACTIVE',
  },
  {
    id: '7',
    slug: 'agricultural-land-bailhongal',
    title: 'Agricultural Land near Bailhongal Road',
    area: 'Bailhongal Road',
    city: 'Belagavi',
    propertyType: 'AGRICULTURAL',
    priceMin: 12000000,
    priceMax: 15000000,
    bedrooms: null,
    bathrooms: null,
    areaSqft: 43560,
    badge: null,
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    status: 'ACTIVE',
  },
  {
    id: '8',
    slug: 'newly-built-3bhk-khanapur',
    title: 'Newly Built 3BHK in Khanapur Road',
    area: 'Khanapur Road',
    city: 'Belagavi',
    propertyType: 'APARTMENT',
    priceMin: 6500000,
    priceMax: 7500000,
    bedrooms: 3,
    bathrooms: 2,
    areaSqft: 1350,
    badge: 'NEW',
    isFeatured: true,
    coverImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    status: 'ACTIVE',
  },
  {
    id: '9',
    slug: 'sold-bungalow-ganeshpur',
    title: 'Independent Bungalow in Ganeshpur',
    area: 'Ganeshpur',
    city: 'Belagavi',
    propertyType: 'HOUSE',
    priceMin: 22000000,
    priceMax: 25000000,
    bedrooms: 5,
    bathrooms: 5,
    areaSqft: 4500,
    badge: 'SOLD',
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    status: 'SOLD',
  },
  {
    id: '10',
    slug: 'affordable-2bhk-udyambag',
    title: 'Affordable 2BHK in Udyambag',
    area: 'Udyambag',
    city: 'Belagavi',
    propertyType: 'APARTMENT',
    priceMin: 3200000,
    priceMax: 3800000,
    bedrooms: 2,
    bathrooms: 1,
    areaSqft: 850,
    badge: null,
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    status: 'ACTIVE',
  },
  {
    id: '11',
    slug: 'premium-4bhk-college-road',
    title: 'Premium 4BHK near College Road',
    area: 'College Road',
    city: 'Belagavi',
    propertyType: 'APARTMENT',
    priceMin: 9500000,
    priceMax: 11000000,
    bedrooms: 4,
    bathrooms: 3,
    areaSqft: 2100,
    badge: 'HOT',
    isFeatured: true,
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    status: 'ACTIVE',
  },
  {
    id: '12',
    slug: 'residential-plot-angol',
    title: 'Residential Plot in Angol',
    area: 'Angol',
    city: 'Belagavi',
    propertyType: 'PLOT',
    priceMin: 4200000,
    priceMax: 4800000,
    bedrooms: null,
    bathrooms: null,
    areaSqft: 1800,
    badge: null,
    isFeatured: false,
    coverImage: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800',
    status: 'ACTIVE',
  },
]

export const mockPropertyDetails: PropertyDetails = {
  id: '1',
  slug: 'premium-2bhk-flat-tilakwadi',
  title: 'Premium 2BHK Flat in Tilakwadi',
  area: 'Tilakwadi',
  city: 'Belagavi',
  propertyType: 'APARTMENT',
  priceMin: 4500000,
  priceMax: 5500000,
  bedrooms: 2,
  bathrooms: 2,
  areaSqft: 980,
  floor: 3,
  totalFloors: 7,
  propertyAge: '1-5 Years',
  furnished: 'SEMI_FURNISHED',
  parking: 1,
  badge: 'FEATURED',
  isFeatured: true,
  status: 'ACTIVE',
  description:
    'Beautiful semi-furnished 2BHK flat located in the heart of Tilakwadi, Belagavi. This property features modern amenities, ample natural light, and is within walking distance of schools, markets, and public transport. The apartment comes with a modular kitchen, marble flooring, and 24/7 water supply. Perfect for families looking for a comfortable living space in a prime location.',
  amenities: [
    'Power Backup',
    'Security',
    'Lift',
    'Park',
    'CCTV',
    'Water Supply 24/7',
    'Gym',
    'Club House',
  ],
  images: [
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
  ],
  coverImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
  // These fields only returned by API for unlocked users:
  address: null, // 'Flat 304, Krishna Apartments, Tilakwadi' — hidden
  latitude: null, // hidden
  longitude: null, // hidden
  ownerName: null, // hidden
  ownerPhone: null, // hidden
  ownerWhatsapp: null, // hidden
}

// Get related properties (exclude current property)
export function getRelatedProperties(
  currentId: string,
  propertyType: string
): Property[] {
  return mockProperties
    .filter((p) => p.id !== currentId)
    .filter((p) => p.propertyType === propertyType || p.status === 'ACTIVE')
    .slice(0, 3)
}
